<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ReliableWebhookDeliveryHub.Infrastructure</RootNamespace>
    <AssemblyName>ReliableWebhookDeliveryHub.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.79.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../3.Applications/ReliableWebhookDeliveryHub.Application/ReliableWebhookDeliveryHub.Application.csproj" />
    <ProjectReference Include="../../1.Domain/ReliableWebhookDeliveryHub.Domain/ReliableWebhookDeliveryHub.Domain.csproj" />
  </ItemGroup>
</Project>
