<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ReliableWebhookDeliveryHub.Application</RootNamespace>
    <AssemblyName>ReliableWebhookDeliveryHub.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../1.Domain/ReliableWebhookDeliveryHub.Domain/ReliableWebhookDeliveryHub.Domain.csproj" />
  </ItemGroup>
</Project>
