<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>ReliableWebhookDeliveryHub.WebApi</RootNamespace>
    <AssemblyName>ReliableWebhookDeliveryHub.WebApi</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.9.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.9.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.7.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../3.Applications/ReliableWebhookDeliveryHub.Application/ReliableWebhookDeliveryHub.Application.csproj" />
    <ProjectReference Include="../../2.Infrastructures/ReliableWebhookDeliveryHub.Infrastructure/ReliableWebhookDeliveryHub.Infrastructure.csproj" />
  </ItemGroup>
</Project>
